[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"
optimizer = true
optimizer_runs = 200

[profile.ci]
verbosity = 4

[rpc_endpoints]
cronos = "https://gateway.nebkas.ro/"
cronos_testnet = "https://cronos-testnet-3.crypto.org:8545/"
goerli = "https://eth-goerli.g.alchemy.com/v2/${GOERLI_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config